### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by lucasgrocha** [lucasgrocha/pokedex#2]
- [x]  Desenvolver um mecanismo de pesquisa de Pokemon por Nome ou Número

- [x] Desenvolver a listagem de Pokemons:
    - [x] Limite de 10 por Exibição
    - [x] Paginação de 10 em 10 itens
- [x] Desenvolver o 'Detalhes' do Pokemon que deverá ser exibido quando um mesmo for clicado. Dentre os detalhes, devem ser exibidos:
    - [x] Nome
    - [x] Imagem
    - [x] Altura
    - [x] Lista de Tipos
    - [x] Velocidade
    - [x] Defesa
    - [x] Ataque
    - [x] HP 
    - [x] Passos da Evolução

Requisitos Extras

- [x] Desenvolver um botão que permite adicionar/remover um pokemon dos Seus Favoritos

- [x] Desenvolver a listagem de Pokemons Favoritos
- [x] Criar o Layout como Responsivo
- [x] Tornar a aplicação um PWA
- [x] Criar o Design similar/fiel ao de uma Pokedex
- [ ] Aplicar Testes Unitários ou Testes E2E
- [ ] Aplicar Redux / Flux Architecture
